# Generated by Django 4.0 on 2022-09-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('web', models.URLField(max_length=500)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
